nacos:
  config:
    auto-refresh: true
    server-addr: 127.0.0.1:8848
    group: DEFAULT_GROUP
    data-id: timedpush-quartz-dev.yaml
    type: yaml
    max-retry: 10
    namespace: 7e6e4304-d172-4ad5-8dfc-455f8e98110a
    bootstrap:
      enable: true